name = "placebo"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:generic".build_args]
build_image = "rust:slim"
run_image = "scratch"

[builders."docker:go"]
enabled = false

[builders."exec:go"]
enabled = false

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "ok"
instances = { min = 1, max = 200, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "abort"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "metrics"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "panic"
instances = { min = 1, max = 250, default = 1 }

[[testcases]]
name = "stall"
instances = { min = 1, max = 250, default = 1 }
